### ISSUE TITLE
F6 and The Make Run Options

### ISSUE THREAD

**Issue by nrs2bear** [tomlau10/gcc-make-run#20] opened 2017-06-28 22:04 UTC
When I press F6, the blue bar shows
gcc-make-run: Running Command... "
g++" "test.cpp" -o "test.exe"
and disappears, nothing more happens, and when I right click to my file on the tree view and click "Make Run", it says
gcc-make-run: Running Command...
"mingw32-make" -f "test.cpp"
gcc-make-run: Compile Error
test.cpp:2: *** missing separator. Stop.

I have installed TDM-GCC and set the mingw32-make like you say on the page. Did I do something wrong? And sorry for my bad english

**Comment by tomlau10** [comment] 2017-07-04 10:09
can you screen capture the package setting page
and paste the content of `test.cpp` here?

**Comment by tomlau10** [comment] 2024-02-15 09:41
this is a bit late but possible duplicate of #17

**Closed as not planned by tomlau10** 2024-02-15 09:41 UTC
