### ISSUE TITLE
 gcc-make-run

### ISSUE THREAD

**Issue by HengDoris** [tomlau10/gcc-make-run#55] opened 2020-02-08 02:16 UTC
It can't be installed .
![image](https://user-images.githubusercontent.com/55883423/74077609-0c2ddb80-4a5c-11ea-871f-88834ed30e39.png)

**Comment by tomlau10** [comment] 2024-02-15 10:28
might be duplicate of #33

**Closed as not planned by tomlau10** 2024-02-15 10:28 UTC
