### ISSUE TITLE
Failed to activate the gcc-make-run package

### ISSUE THREAD

**Issue by Coriander-No** [tomlau10/gcc-make-run#51] opened 2019-02-03 06:44 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [gcc-make-run](https://github.com/tomlau10/gcc-make-run) package 0.2.12

### Stack Trace

Failed to activate the gcc-make-run package

```
At Cannot find module 'atom-space-pen-views'

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/gcc-make-run/lib/gcc-make-run-view.coffee:8:13)
    at /packages/gcc-make-run/lib/gcc-make-run-view.coffee:1:1)
    at /packages/gcc-make-run/lib/gcc-make-run-view.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/gcc-make-run/lib/gcc-make-run.coffee:7:18)
    at /packages/gcc-make-run/lib/gcc-make-run.coffee:1:1)
    at /packages/gcc-make-run/lib/gcc-make-run.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:641362)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3029314)
    at Package.activateNow (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017448)
    at measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017226)
    at Package.measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3014857)
```

### Commands

```
```

### Non-Core Packages

```
atom-python-run 0.9.7 
autocomplete-python 1.10.5 
busy-signal 2.0.0 
docblockr 0.13.7 
file-icons 2.1.27 
gcc-make-run 0.2.12 
intentions 1.1.5 
language-matlab 0.2.1 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
seti-icons 1.5.4 
simplified-chinese-menu 5.3.5 
```

**Comment by tomlau10** [comment] 2024-02-15 10:27
duplicate of #33

**Closed as not planned by tomlau10** 2024-02-15 10:27 UTC
Labels: duplicate
