### ISSUE TITLE
gcc-make-run doesn't work

### ISSUE THREAD

**Issue by ghost** [tomlau10/gcc-make-run#4] opened 2016-04-19 19:17 UTC
I am using Windows 10 version 1511, build 10586 and [Atom 1.7.2](https://github.com/atom/atom/releases/tag/v1.7.2), but gcc-make-run doesn't run in [Atom 1.7.2](https://github.com/atom/atom/releases/tag/v1.7.2). It shows `gcc-make-run: Fail`, I don't know why. With [Atom 1.6.2](https://github.com/atom/atom/releases/tag/v1.6.2), gcc-make-run works well.

**Comment by tomlau10** [comment] 2016-04-23 07:41
I will look into the issue when I have time, currently I am dealing with my final year project and exam period haha

**Comment by ghost** [comment] 2016-04-23 10:39
Ok!

**Comment by xiaotian666** [comment] 2016-04-27 07:05
gcc-make-run: Running Command... but no terminal(CMD)
what's the matter?

**Comment by tomlau10** [comment] 2016-04-29 13:08
@torn4dom4n 
- I cannot reproduce the issue on my win10 notebook with the same environment as you
- are there any errors in the dev console ? (default shortcut: ctrl + alt + i)

@xiaotian666 
- did the terminal pop up and close immediately or did not pop up at all ?
- did you use a lot of quotes in the compile flags or arguments (in ctrl+f6 view) ?

**Comment by xiaotian666** [comment] 2016-05-01 14:17
#### I found the problem ——the“gcc-make-run” and the"python-tools" has conflicts,bat I don't know how to  solve it.so I deleted the"python tools". @tomlau10

**Comment by tomlau10** [comment] 2016-05-02 06:02
@xiaotian666 
Thanks. I found that this is really an issue of `python-tools` which overwrites the `PATH` environment variable and causes `child_process.exec()` not working properly.
see MichaelAquilina/python-tools#37

**Comment by ghost** [comment] 2016-05-03 15:08
@tomlau10 I think because of `atom.cmd` and it fixed [Atom 1.7.3](https://github.com/atom/atom/releases/tag/v1.7.3). Now it has worked!

**Comment by tomlau10** [comment] 2016-05-03 15:32
@torn4dom4n oic~ so I will close this issue for now :)

**Closed as completed by tomlau10** 2016-05-03 15:32 UTC

**Comment by Adobe-Android** [comment] 2016-05-03 16:19
Ya, I noticed it broke too. I just disabled it for a while because I knew you were busy. I'm just using Atom Beta for now...it works with that.

**Comment by Mry3ll0w** [comment] 2019-03-20 08:49
I've got  a problem in the compilation process , probably due to a bad setup in the settings , literally it shows me an error saying "gcc-make-run: Compile Error", showing me the code itself not a concrete error, help me pls ;(
